sistema/cliente/urls.py
from django.urls import path
from . import views
from django.conf import settings



app_name = 'cliente'

# urlpatterns a lista de roteamentos de URLs para funções/Views
urlpatterns = [
    path("", views.IndexView.as_view(), name="index",),
    path("cadastrar", views.ClienteCreateView.as_view(), name='cadastrar'),
    path("exportar", views.DataExportView.as_view(), name='exportar'),
    path("lista", views.ListaListView.as_view(), name='lista'),
    path("editar/<int:pk>", views.EditaClienteView.as_view(), name="edita"),
]

sistema/sistema1/urls.py
from django.urls.conf import include
from django.contrib import admin
from django.urls import path

app_name = "app"

urlpatterns = [
    # URL padrão
    path('', include('cliente.urls')),

    # Interface administrativa
    path('admin/', admin.site.urls),
]

sistema/cliente/models.py
from django.db import models
from django.conf import settings
from  django.utils.timezone import timezone

class clientes(models.Model):

  STATUS = (
    (0, ("Inativo")), 
    (1, ("Ativo"))
  )

  nome = models.CharField(
    max_length=255,
    null=False,
    blank=False,
    verbose_name="Nome"
  )
  
  email = models.EmailField(
    default=' ',
    unique=True,
    max_length=255,
    null=False,
    blank=False,
    verbose_name="E-mail"
  )

  cpf = models.CharField(
    unique=True,
    max_length=11,
    null=False,
    blank=False,
    verbose_name="CPF"
  )
  
  nome_mae = models.CharField(
    max_length=255,
    null=False,
    blank=False,
    verbose_name="Nome Mãe"
  )

  rg = models.CharField(
    max_length=11,
    null=False,
    blank=False,
    verbose_name="RG"
  )

  telefone = models.CharField(
    max_length=11,
    null=False,
    blank=False,
    verbose_name="Telefone"
  )
  
  rua = models.CharField(
    max_length=255,
    null=False,
    blank=False,
    verbose_name="Rua"
  )
  
  bairro = models.CharField(
    max_length=255,
    null=False,
    blank=False,
    verbose_name="Bairro"
  )

  cidade = models.CharField(
    default=' ',
    max_length=255,
    null=False,
    blank=False,
    verbose_name="Cidade"
  )

  estado = models.CharField(
    max_length=255,
    null=False,
    blank=False,
    verbose_name="Estado"
  )
  
  numero = models.IntegerField(
    null=False,
    blank=False,
    verbose_name="Número Residencia"
  )

  estado_civil = models.CharField(
    max_length=255,
    null=False,
    blank=False,
    verbose_name="Estado Civil"
  )

  situacao = models.IntegerField(
    choices=STATUS, 
    default=1, 
    verbose_name="Situação"
  )

  class Meta:
    verbose_name = "clientes"
    verbose_name_plural = "cliente"
    
  def __str__(self):
    return self.nome

sistema/cliente/forms.py
from django import forms
from .models import clientes

class InsereClienteForm(forms.ModelForm):
  class Meta:
    # Modelo base
    model = clientes

    # Campos que estarão no form
    fields = [
     'nome',
      'cpf',
      'rg',
      'email',
      'nome_mae',
      'telefone',
      'rua',
      'bairro',
      'numero',
      'cidade',
      'estado',
      'estado_civil',
      'situacao'
    ]

    widgets = {
      "nome": forms.TextInput(attrs={"class": "form-control"}),
      "cpf": forms.TextInput(attrs={"class": "form-control"}),
      "rg": forms.TextInput(attrs={"class": "form-control"}),
      "email": forms.TextInput(attrs={"class": "form-control"}),
      "nome_mae": forms.TextInput(attrs={"class": "form-control"}),
      "telefone": forms.TextInput(attrs={"class": "form-control"}),
      "rua": forms.TextInput(attrs={"class": "form-control"}),
      "bairro": forms.TextInput(attrs={"class": "form-control"}),
      "numero": forms.TextInput(attrs={"class": "form-control"}),
      "estado": forms.TextInput(attrs={"class": "form-control"}),
      "cidade": forms.TextInput(attrs={"class": "form-control"}),
      "estado_civil": forms.TextInput(attrs={"class": "form-control"}),
      "situacao": forms.Select(attrs={"class": "form-control"}),
    }

sistema/cliente/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.http import HttpResponse
from django.views.generic import CreateView, ListView, UpdateView, FormView, DetailView, TemplateView
from django.utils import timezone

from csv_export.views import CSVExportView

from .forms import InsereClienteForm
from .models import clientes


class IndexView(TemplateView):
  template_name = "index.html"

class ClienteCreateView(CreateView):
  template_name = "cadastrar.html"
  model = clientes
  form_class = InsereClienteForm
  success_url = reverse_lazy("cliente:index")


class DataExportView(CSVExportView):
  model = clientes
  fields = ('nome','cpf', 'email', 'telefone', 'situacao')
  header = False
  specify_separator = False
 

  def get_filename(self, queryset):
    return 'importa.csv'


class ListaListView(TemplateView):
  template_name = "lista.html"

  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    context["Clientes"] = clientes.objects.all()
    return context


class EditaClienteView(UpdateView):
  template_name = "cadastrar.html"
  model = clientes
  form_class = InsereClienteForm
  success_url = reverse_lazy("cliente:index")

  def get(self, request, *args, **kwargs):
      self.object = self.get_object()
      form = self.form_class(instance=self.object)
      return self.render_to_response(self.get_context_data(form=form))

  def post(self, request, *args, **kwargs):
      self.object = self.get_object()
      form_class = self.get_form_class()
      form = form_class(request.POST, instance=self.object)
      if form.is_valid():
          self.object = form.save()
          return self.form_valid(form)
      return self.form_invalid(form)

sistema/cliente/templates/base.html
<!DOCTYPE html>
<html>
  
  <head>
    <!-- Title -->
    <title>
      {% block title %}Sistema de Cadastro de Clientes do Hotel{% endblock %}
    </title>


    <!-- Arquivos CSS -->
    {% load static %}
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- Bloco de Estilos -->
    {% block styles %}{% endblock %}
  </head>

  <body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <button class="navbar-toggler" type="button" 
          data-toggle="collapse" data-target="#conteudo-navbar" 
          aria-controls="conteudo-navbar" aria-expanded="false" 
          aria-label="Ativar navegação">
          <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="conteudo-navbar">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'cliente:index' %}">
                  Página Inicial
                </a>
            </li>
            <!-- <li class="nav-item">
              <a class="nav-link" href="{% url 'cliente:index' %}">
                Cadastrar
              </a>
            </li> -->
          </ul>           
      </div>
    </nav>
      
    <!-- Bloco de conteúdo -->
    {% block conteudo %}{% endblock %}

    <!-- Arquivos necessários para o Bootstrap -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o" crossorigin="anonymous"></script>
    <!-- Bloco de scripts -->
    {% block scripts %}{% endblock %}

    <!-- Scripts.js -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    
  </body>
</html>

sistema/cliente/templates/cadastrar.html
<!-- Estendemos do template base -->
{% extends "base.html" %}

<!-- Bloco que define o <title></title> da nossa página -->
{% block title %}Página Inicial{% endblock %}

<!-- Bloco de conteúdo da nossa página -->    
{% block conteudo %}
  <div class="container">
    <div class="row">
      <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
          <div class="card-body">
            <form method="post">
              {% csrf_token %}

              {{ form }}

              <br>
              <div class="form-group">
                <div class="text-center"> 
                  <button type="submit"  class="btn btn-primary" >Salvar</button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

sistema/cliente/templates/index.html
<!-- Estendemos do template base -->
{% extends "base.html" %}

<!-- Bloco que define o <title></title> da nossa página -->
{% block title %}Página Inicial{% endblock %}

<!-- Bloco de conteúdo da nossa página -->    
{% block conteudo %}
<div class="container">
  <div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Cadastrar Cliente</h5>
          <p class="card-text">
            Cadastre aqui um novo <code>Cliente</code>.
          </p>
          <a href="{% url 'cliente:cadastrar' %}" class="btn btn-primary">
            Novo Cliente
          </a>
        </div>
      </div>
    </div>
    
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Listar Clientes</h5>
          <p class="card-text">
            <code>Lista</code>  de Clientes.
          </p>
          <a href="{% url 'cliente:lista' %}"
              class="btn btn-primary">
            Lista
          </a>
        </div>
      </div>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Exportar Clientes</h5>
          <p class="card-text">
            <code>Exportar</code> Lista de Clientes.
          </p>
          <a href="{% url 'cliente:exportar' %}"
              class="btn btn-primary">
            Exportar
          </a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

sistema/cliente/templates/lista.html
<!-- Estendemos do template base -->
{% extends "base.html" %}

<!-- Bloco que define o <title></title> da nossa página -->
{% block title %}Lista Cliente{% endblock %}

<!-- Bloco de conteúdo da nossa página -->    
{% block conteudo %}
  <div class="container">
    <div class="row">
      <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
          <div class="card-body">
            {% for Cliente in Clientes  %}
                <a href="{% url 'cliente:edita' Cliente.id %}">
                    <b>Nome :</b> {{ Cliente.nome }}
                <a>
                <br><br>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}